name: Developer_Branch_CI

on:
  push:
    branches:
      - 'XPNS-*'

jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    group: default
    steps:
      - uses: actions/checkout@v3
      - run: env




