name: Pull_Request_CI
on:
  pull_request:
    branches:
      - 'main'
jobs:
  check-bats-version:
    runs-on: self-hosted
    steps:
      - name: checkout
      - uses: actions/checkout@v4
      - run: ls
      - run: tail index.js